language: ruby
rvm:
- 2.6.5
cache:
  bundler: true
  yarn: true
  directories:
  - "/home/travis/.rvm/"
before_install:
- gem install bundler
- gem update bundler
before_script:
- psql -c 'create database app_rate_test;' -U postgres
script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: bMmTTOmvp0ZqDLhqp3MQTqyMFVtHnTPvRsj2rU0UBunQZIqzmV6GmmWPtlgg+544mvDRnFuq6+vrM5ig97a2AnVzFqklAwRjhLE7NLh2/hOswIEeKEb3G6a6AlLbTbNvYvfN8pKp0fkMUD+t/1BVY3kob6Yl8TWfGaCrSwjQbijUQvv+BoggMMM+IWFAUTYficKa/2Bxud4t8hn4i/79yYnCIcMBCCxqOmmZQBF02lDjDSgEGqFjc2HgIsUmYrKmeOVFK0TwEUvPlAEEjW6qE4CJHryi5WY0UHISjzzl/41XXHHbvH32Z1bHBPEWsGtUwcfCgwPcKDpEjbF9nX3OGXC4wytb1NFMpH69xqalf3G3hW5wJ/EJhsysRUV6MRUuhmldgrLYOD/aN8cxp0xpOkjNtH+YYaWNrfGfkRVq3pT9JtKcxgFlcX8CNg2QHSvYcovOELgbNGozNf0UY8t99pyPd1VzRWpllyXhiZ5GNlEFAc1TFfMff58P+BXaVAALZZn2TH3z+xMgpQEhst5I3hDrUqw1tCta4Xd1VgwyOFtuOg9ye7ETHNEK/gOoytA4zCpcnqSM+3FoGcPhyBOBiDCnb1nkZI72UpihbdI54XVTfG1hhsu0/ft+S5rV5tNZKaPRpPPmHjq+9nhOMaP+HlW4yieyI3mBX+TUXmTm+2c=
  app: apprate
  on:
    repo: c100bit/app_rate
services:
- postgresql
- redis-server
